source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.4'

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem 'sprockets-rails'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem 'importmap-rails'

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem 'turbo-rails'

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem 'stimulus-rails'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem 'jbuilder'

# Use Redis adapter to run Action Cable in production
# gem "redis", "~> 4.0"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Sass to process CSS
# gem "sassc-rails"

# A ruby implementation of the RFC 7519 OAuth JSON Web Token (JWT) standard
gem 'jwt'

# bcrypt-ruby is a Ruby binding for the OpenBSD bcrypt() password hashing algorithm, allowing you to easily store a
# secure hash of your users' passwords. (also provides #has_secure_password method to models)
gem 'bcrypt'

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Rack Middleware for handling Cross-Origin Resource Sharing (CORS), which makes cross-origin AJAX possible.
gem 'rack-cors'

# This gem lets your API users pass in and receive camelCased or dash-cased keys, while your Rails app receives and
# produces snake_cased ones.
gem 'olive_branch'

# Authorization framework for Ruby/Rails applications
gem 'action_policy'

# Takes some boilerplate out of Ruby with methods like attr_initialize.
gem 'attr_extras'

# Repository for collecting Locale data for Ruby on Rails I18n as well as other interesting, Rails related I18n stuff
gem 'rails-i18n'

# A ruby library/gem for interacting with .docx files
gem 'docx'

# Pluggable Ruby translation framework
gem 'mobility'

# Ruby gem for creating letter avatar from user's name (or any other string :-) ).
gem 'letter_avatar'

# Ruby gem that converts office documents to PDF using LibreOffice / OpenOffice.
# NOTE: LibreOffice packge must be installed
gem 'libreconv'

# A library for bulk insertion of data into your database using ActiveRecord.
gem 'activerecord-import'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem 'debug', platforms: %i[mri mingw x64_mingw]

  # Behaviour Driven Development for Ruby (Adding it to the :development group is not strictly necessary,
  # but without it, generators and rake tasks must be preceded by RAILS_ENV=test.)
  gem 'rspec-rails', '~> 6.0.0'

  # factory_bot is a fixtures replacement with a straightforward definition syntax, support for multiple build
  # strategies, and support for multiple factories for the same class, including factory inheritance
  gem 'factory_bot_rails'

  # A library for generating fake data such as names, addresses, and phone numbers.
  gem 'faker'
end

group :development, :test, :e2e do
  # Strategies for cleaning databases in Ruby. Can be used to ensure a clean state for testing.
  gem 'database_cleaner-active_record'

  # A gem providing "time travel", "time freezing", and "time acceleration" capabilities, making it simple to test
  # time-dependent code. It provides a unified method to mock Time.now, Date.today, and DateTime.now in a single call.
  gem 'timecop'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem 'web-console'

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"

  # A Ruby static code analyzer and formatter, based on the community Ruby style guide
  gem 'rubocop'

  # A RuboCop extension focused on enforcing Rails best practices and coding conventions.
  gem 'rubocop-rails', require: false

  # Code style checking for RSpec files
  gem 'rubocop-rspec', require: false
end

group :test, :e2e do
  # Code coverage for Ruby with a powerful configuration library and automatic merging of coverage across test suites
  gem 'simplecov', require: false
end
