# Tests related to frontend

name: Frontend CI

on:
  push:
    branches: [main]

jobs:
  lint:
    # TODO: Enable when CI integration is completed
    if: ${{ false }}

    name: Linters
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup & cache Node
        uses: actions/setup-node@v2
        with:
          node-version: "v16.14.0"
          cache: 'yarn'
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn format:check

      - name: Run Typescript
        run: yarn tsc
