# E2E Tests

name: E2E Tests

on:
  push:
    branches: [main]

jobs:
  test:
    name: Playwright
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./e2e

    steps:
      - uses: actions/checkout@v3

      - name: Setup & run App
        run: docker-compose --file ../docker-compose.e2e.yml up --build --detach

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "v16.14.0"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Create database
        run: docker exec vtjmk_e2e bundle exec rails db:create db:schema:load

      - name: Run Playwright tests
        run: yarn playwright test
        env:
          APP_URL: 'http://localhost:3001'

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30
